In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("advertising (1).csv")

In [ ]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:

df.isna().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [ ]:
df.corr()

                 TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [ ]:
df.drop("Newspaper", axis=1, inplace= True)

In [ ]:
df.head()

      TV  Radio  Sales
0  230.1   37.8   22.1
1   44.5   39.3   10.4
2   17.2   45.9   12.0
3  151.5   41.3   16.5
4  180.8   10.8   17.9

In [ ]:
df.shape

(200, 3)

In [ ]:
x= df [['TV','Radio']]
y= df [["Sales"]]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=18)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
model.coef_

array([[0.05380296, 0.10026216]])

In [ ]:
model.intercept_

array([4.92234707])

In [ ]:
y_pred_train = model.predict(X_train)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
from math import sqrt

In [ ]:
sqrt(mean_squared_error(y_train, y_pred_train))

1.5549843898359268

In [ ]:
r2_score(y_train, y_pred_train)

0.9064140121341553

In [ ]:
y_pred_test = model.predict(X_test)

In [ ]:
sqrt(mean_squared_error(y_test, y_pred_test))

1.9838154465586977

In [ ]:
r2_score(y_test, y_pred_test)

0.8889004520739148

In [ ]:
def sales_predict(tv, radio):
    predicted_sale = model.predict([[tv, radio]])
    return predicted_sale[0][0]

In [ ]:
tv = float(input('Enter budget for tv: '))
radio = float(input('Enter budget for radio: '))

print(f"Predicted Sale: {round(sales_predict(tv, radio))}")

Enter budget for tv: 23
Enter budget for radio: 12
Predicted Sale: 7

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
df.TV.min(), df.TV.max()

In [ ]:
df.Radio.min(), df.Radio.max()

(0.0, 49.6)